sonar.projectKey=karan150602_8.2CDevSecOps
sonar.organization=karan150602
sonar.host.url=https://sonarcloud.io
sonar.login=${a0de569b4ecfe36c4967bbde449c41865a36e6ec}
sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8

